Modification performed in 'blog.css' file
ProjectSakura/ProjectSakura.github.io pull request #263
Opened 2021-04-17 17:53 UTC by Kavs-123

2021-04-17 18:02 UTC, ArunTeltia requested changes

2021-04-17 18:02 UTC, ArunTeltia commented on css/blog.css
> -  transition: all 300ms ease-in-out;
Add this back

2021-04-17 18:02 UTC, ArunTeltia commented on css/blog.css
>    body.layout-one-column-narrow .site-content {
Remove this as well

2021-04-17 18:02 UTC, ArunTeltia commented on css/blog.css
>    .content-area {
remove this as well

2021-04-17 18:02 UTC, ArunTeltia commented on css/blog.css
>  #tertiary {
remove this as well

2021-04-17 18:03 UTC, yasharth291 approved these changes

2021-04-18 02:49 UTC, ArunTeltia commented
I tested @LordShenron Can be merged, Size down by (0.05mb)

2021-04-18 08:56 UTC, merged